/**
 * Demo Data
 * 
 * Centralized location for all demo data used in demo mode.
 * This ensures consistency across the application and makes it easy to update demo data.
 */

// ============================================================================
// VENDOR DEMO DATA
// ============================================================================
export const demoVendors = [
  {
    id: '1',
    name: 'Grand Convention Center',
    serviceType: 'Venue',
    category: 'Venue',
    rating: 4.8,
    totalContracts: 12,
    totalSpent: 450000,
    phone: '+1 (555) 123-4567',
    email: 'bookings@grandconvention.com',
    contactPerson: 'John Smith',
    gstNumber: 'GST123456',
    status: 'active',
    lastContract: new Date('2024-02-15'),
    createdAt: new Date('2023-01-15'),
    updatedAt: new Date('2024-02-15'),
  },
  {
    id: '2',
    name: 'Premium Catering Co.',
    serviceType: 'Catering',
    category: 'Catering',
    rating: 4.9,
    totalContracts: 18,
    totalSpent: 285000,
    phone: '+1 (555) 234-5678',
    email: 'info@premiumcatering.com',
    contactPerson: 'Sarah Johnson',
    gstNumber: 'GST234567',
    status: 'active',
    lastContract: new Date('2024-02-10'),
    createdAt: new Date('2023-02-01'),
    updatedAt: new Date('2024-02-10'),
  },
  {
    id: '3',
    name: 'AdTech Solutions',
    serviceType: 'Marketing',
    category: 'Marketing',
    rating: 4.6,
    totalContracts: 8,
    totalSpent: 125000,
    phone: '+1 (555) 345-6789',
    email: 'sales@adtechsolutions.com',
    contactPerson: 'Mike Davis',
    gstNumber: 'GST345678',
    status: 'active',
    lastContract: new Date('2024-02-05'),
    createdAt: new Date('2023-03-15'),
    updatedAt: new Date('2024-02-05'),
  },
  {
    id: '4',
    name: 'Entertainment Plus',
    serviceType: 'Entertainment',
    category: 'Entertainment',
    rating: 4.7,
    totalContracts: 15,
    totalSpent: 195000,
    phone: '+1 (555) 456-7890',
    email: 'bookings@entertainmentplus.com',
    contactPerson: 'Emily Chen',
    gstNumber: 'GST456789',
    status: 'active',
    lastContract: new Date('2024-01-28'),
    createdAt: new Date('2023-04-01'),
    updatedAt: new Date('2024-01-28'),
  },
  {
    id: '5',
    name: 'Tech Events Pro',
    serviceType: 'Technology',
    category: 'Technology',
    rating: 4.5,
    totalContracts: 10,
    totalSpent: 98000,
    phone: '+1 (555) 567-8901',
    email: 'contact@techeventspro.com',
    contactPerson: 'Robert Wilson',
    gstNumber: 'GST567890',
    status: 'active',
    lastContract: new Date('2024-01-15'),
    createdAt: new Date('2023-05-10'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '6',
    name: 'EventStaff Plus',
    serviceType: 'Staffing',
    category: 'Staffing',
    rating: 4.4,
    totalContracts: 22,
    totalSpent: 176000,
    phone: '+1 (555) 678-9012',
    email: 'hr@eventstaffplus.com',
    contactPerson: 'Jennifer Lee',
    gstNumber: 'GST678901',
    status: 'active',
    lastContract: new Date('2024-02-01'),
    createdAt: new Date('2023-06-20'),
    updatedAt: new Date('2024-02-01'),
  },
];

// ============================================================================
// EVENT DEMO DATA
// ============================================================================
export const demoEvents = [
  {
    id: '1',
    name: 'Annual Tech Conference 2024',
    type: 'conference',
    startDate: '2024-03-15',
    endDate: '2024-03-17',
    location: 'San Francisco, CA',
    venue: 'Moscone Center',
    attendees: 500,
    budget: 85000,
    spent: 62000,
    organizer: 'Sarah Johnson',
    client: 'Tech Corp',
    description: 'Annual technology conference featuring keynote speakers and workshops',
    status: 'active',
    createdAt: '2024-01-15',
    updatedAt: '2024-03-10',
    assignments: [],
    _count: { files: 5, budgetItems: 12, activityLogs: 8 },
  },
  {
    id: '2',
    name: 'Product Launch Event',
    type: 'launch',
    startDate: '2024-03-20',
    endDate: null,
    location: 'New York, NY',
    venue: 'Hudson Yards',
    attendees: 200,
    budget: 45000,
    spent: 12000,
    organizer: 'Mike Davis',
    client: 'Product Inc',
    description: 'Launching our new product line with media and influencers',
    status: 'planning',
    createdAt: '2024-02-01',
    updatedAt: '2024-02-15',
    assignments: [],
    _count: { files: 2, budgetItems: 8, activityLogs: 3 },
  },
  {
    id: '3',
    name: 'Team Building Retreat',
    type: 'retreat',
    startDate: '2024-04-10',
    endDate: '2024-04-12',
    location: 'Lake Tahoe, NV',
    venue: 'Mountain Resort',
    attendees: 50,
    budget: 25000,
    spent: 5000,
    organizer: 'Emily Chen',
    client: 'Retreat Co',
    description: 'Company-wide team building activities and workshops',
    status: 'planning',
    createdAt: '2024-01-20',
    updatedAt: '2024-02-10',
    assignments: [],
    _count: { files: 3, budgetItems: 6, activityLogs: 5 },
  },
  {
    id: '4',
    name: 'Annual Gala',
    type: 'gala',
    startDate: '2024-02-28',
    endDate: '2024-02-28',
    location: 'Chicago, IL',
    venue: 'Grand Ballroom',
    attendees: 350,
    budget: 95000,
    spent: 87000,
    organizer: 'Robert Wilson',
    client: 'Gala Corp',
    description: 'Annual company gala with dinner and entertainment',
    status: 'active',
    createdAt: '2024-01-10',
    updatedAt: '2024-02-25',
    assignments: [],
    _count: { files: 8, budgetItems: 15, activityLogs: 12 },
  },
  {
    id: '5',
    name: 'Workshop Series',
    type: 'workshop',
    startDate: '2024-01-20',
    endDate: '2024-01-22',
    location: 'Seattle, WA',
    venue: 'Convention Center',
    attendees: 150,
    budget: 45000,
    spent: 44500,
    organizer: 'Lisa Anderson',
    client: 'Workshop Co',
    description: 'Educational workshop series for team development',
    status: 'completed',
    createdAt: '2023-12-15',
    updatedAt: '2024-01-25',
    assignments: [],
    _count: { files: 4, budgetItems: 10, activityLogs: 6 },
  },
  {
    id: '6',
    name: 'Summer Networking Mixer',
    type: 'networking',
    startDate: '2024-06-15',
    endDate: null,
    location: 'Miami, FL',
    venue: 'Beachfront Hotel',
    attendees: 120,
    budget: 30000,
    spent: 5000,
    organizer: 'David Martinez',
    client: 'Network Pro',
    description: 'Networking event for industry professionals',
    status: 'planning',
    createdAt: '2024-02-20',
    updatedAt: '2024-02-20',
    assignments: [],
    _count: { files: 1, budgetItems: 5, activityLogs: 2 },
  },
  {
    id: '7',
    name: 'Client Appreciation Dinner',
    type: 'dinner',
    startDate: '2024-04-10',
    endDate: '2024-04-10',
    location: 'Boston, MA',
    venue: 'Fine Dining Restaurant',
    attendees: 80,
    budget: 35000,
    spent: 15000,
    organizer: 'Jennifer Lee',
    client: 'Client Relations',
    description: 'Exclusive dinner for top clients',
    status: 'active',
    createdAt: '2024-02-15',
    updatedAt: '2024-03-05',
    assignments: [],
    _count: { files: 3, budgetItems: 7, activityLogs: 4 },
  },
  {
    id: '8',
    name: 'Training Seminar',
    type: 'seminar',
    startDate: '2024-03-25',
    endDate: '2024-03-25',
    location: 'Austin, TX',
    venue: 'Training Center',
    attendees: 100,
    budget: 28000,
    spent: 18000,
    organizer: 'Michael Brown',
    client: 'Training Solutions',
    description: 'Professional development training session',
    status: 'active',
    createdAt: '2024-02-05',
    updatedAt: '2024-03-15',
    assignments: [],
    _count: { files: 2, budgetItems: 6, activityLogs: 3 },
  },
  {
    id: '9',
    name: 'Charity Fundraiser',
    type: 'fundraiser',
    startDate: '2024-05-20',
    endDate: '2024-05-20',
    location: 'Los Angeles, CA',
    venue: 'Event Hall',
    attendees: 250,
    budget: 60000,
    spent: 8000,
    organizer: 'Patricia Garcia',
    client: 'Charity Foundation',
    description: 'Annual charity fundraising event',
    status: 'planning',
    createdAt: '2024-03-01',
    updatedAt: '2024-03-20',
    assignments: [],
    _count: { files: 4, budgetItems: 11, activityLogs: 5 },
  },
  {
    id: '10',
    name: 'Industry Summit',
    type: 'summit',
    startDate: '2024-04-05',
    endDate: '2024-04-07',
    location: 'Las Vegas, NV',
    venue: 'Convention Center',
    attendees: 800,
    budget: 150000,
    spent: 95000,
    organizer: 'James Taylor',
    client: 'Summit Organizers',
    description: 'Multi-day industry summit with panels and networking',
    status: 'active',
    createdAt: '2024-01-20',
    updatedAt: '2024-03-28',
    assignments: [],
    _count: { files: 7, budgetItems: 18, activityLogs: 10 },
  },
];

// Dashboard Events (simplified version for dashboard)
export const demoDashboardEvents = [
  {
    id: '1',
    name: 'Annual Tech Conference 2024',
    description: 'Annual technology conference featuring keynote speakers and workshops',
    client: 'Tech Corp',
    status: 'Active',
    startDate: '2024-03-15',
    endDate: '2024-03-17',
    createdAt: '2024-01-15',
    _count: { files: 5, budgetItems: 12, activityLogs: 8 },
  },
  {
    id: '2',
    name: 'Product Launch Event',
    description: 'Launching our new product line with media and influencers',
    client: 'Product Inc',
    status: 'Planning',
    startDate: '2024-03-20',
    endDate: null,
    createdAt: '2024-02-01',
    _count: { files: 2, budgetItems: 8, activityLogs: 3 },
  },
  {
    id: '3',
    name: 'Annual Gala',
    description: 'Annual company gala with dinner and entertainment',
    client: 'Gala Corp',
    status: 'Active',
    startDate: '2024-02-28',
    endDate: '2024-02-28',
    createdAt: '2024-01-10',
    _count: { files: 8, budgetItems: 15, activityLogs: 12 },
  },
  {
    id: '4',
    name: 'Workshop Series',
    description: 'Educational workshop series for team development',
    client: 'Workshop Co',
    status: 'Completed',
    startDate: '2024-01-20',
    endDate: '2024-01-22',
    createdAt: '2023-12-15',
    _count: { files: 4, budgetItems: 10, activityLogs: 6 },
  },
  {
    id: '5',
    name: 'Summer Networking Mixer',
    description: 'Networking event for industry professionals',
    client: 'Network Pro',
    status: 'Planning',
    startDate: '2024-06-15',
    endDate: null,
    createdAt: '2024-02-20',
    _count: { files: 1, budgetItems: 5, activityLogs: 2 },
  },
  {
    id: '6',
    name: 'Holiday Party 2023',
    description: 'Annual holiday celebration for employees',
    client: 'Holiday Events',
    status: 'Completed',
    startDate: '2023-12-15',
    endDate: '2023-12-15',
    createdAt: '2023-11-01',
    _count: { files: 6, budgetItems: 9, activityLogs: 7 },
  },
  {
    id: '7',
    name: 'Client Appreciation Dinner',
    description: 'Exclusive dinner for top clients',
    client: 'Client Relations',
    status: 'Active',
    startDate: '2024-04-10',
    endDate: '2024-04-10',
    createdAt: '2024-02-15',
    _count: { files: 3, budgetItems: 7, activityLogs: 4 },
  },
  {
    id: '8',
    name: 'Training Seminar',
    description: 'Professional development training session',
    client: 'Training Solutions',
    status: 'Active',
    startDate: '2024-03-25',
    endDate: '2024-03-25',
    createdAt: '2024-02-05',
    _count: { files: 2, budgetItems: 6, activityLogs: 3 },
  },
  {
    id: '9',
    name: 'Charity Fundraiser',
    description: 'Annual charity fundraising event',
    client: 'Charity Foundation',
    status: 'Planning',
    startDate: '2024-05-20',
    endDate: '2024-05-20',
    createdAt: '2024-03-01',
    _count: { files: 4, budgetItems: 11, activityLogs: 5 },
  },
  {
    id: '10',
    name: 'Industry Summit',
    description: 'Multi-day industry summit with panels and networking',
    client: 'Summit Organizers',
    status: 'Active',
    startDate: '2024-04-05',
    endDate: '2024-04-07',
    createdAt: '2024-01-20',
    _count: { files: 7, budgetItems: 18, activityLogs: 10 },
  },
  {
    id: '11',
    name: 'Team Offsite',
    description: 'Quarterly team offsite meeting',
    client: 'Internal',
    status: 'Completed',
    startDate: '2024-01-10',
    endDate: '2024-01-12',
    createdAt: '2023-12-01',
    _count: { files: 3, budgetItems: 8, activityLogs: 4 },
  },
  {
    id: '12',
    name: 'Marketing Campaign Launch',
    description: 'Launch event for new marketing campaign',
    client: 'Marketing Dept',
    status: 'Active',
    startDate: '2024-03-30',
    endDate: null,
    createdAt: '2024-02-10',
    _count: { files: 5, budgetItems: 9, activityLogs: 6 },
  },
];

// Reports Events (simplified for reports page)
export const demoReportsEvents = [
  {
    id: '1',
    name: 'Tech Conference 2024',
    client: 'Tech Corp',
    status: 'active',
    startDate: '2024-03-15',
    endDate: '2024-03-15',
  },
  {
    id: '2',
    name: 'Product Launch Event',
    client: 'Product Inc',
    status: 'planning',
    startDate: '2024-04-20',
    endDate: '2024-04-20',
  },
  {
    id: '3',
    name: 'Annual Gala',
    client: 'Gala Corp',
    status: 'active',
    startDate: '2024-02-28',
    endDate: '2024-02-28',
  },
];

// Analytics Events (simplified for analytics)
export const demoAnalyticsEvents = [
  {
    id: '1',
    name: 'Tech Conference 2024',
    status: 'active',
    createdAt: '2024-01-15',
    _count: { budgetItems: 12 },
  },
  {
    id: '2',
    name: 'Product Launch Event',
    status: 'planning',
    createdAt: '2024-02-01',
    _count: { budgetItems: 8 },
  },
  {
    id: '3',
    name: 'Annual Gala',
    status: 'active',
    createdAt: '2024-01-10',
    _count: { budgetItems: 15 },
  },
  {
    id: '4',
    name: 'Workshop Series',
    status: 'completed',
    createdAt: '2023-12-01',
    _count: { budgetItems: 6 },
  },
];

// ============================================================================
// EXPENSE DEMO DATA
// ============================================================================
export const demoExpenses = [
  {
    id: 1,
    eventName: 'Annual Tech Conference 2024',
    category: 'Venue',
    description: 'Conference Hall Deposit',
    vendor: 'Grand Convention Center',
    amount: 15000,
    date: '2024-02-01',
    submittedBy: 'John Smith',
    status: 'approved',
    approvedBy: 'Sarah Johnson',
    approvalDate: '2024-02-02',
  },
  {
    id: 2,
    eventName: 'Annual Tech Conference 2024',
    category: 'Marketing',
    description: 'Social Media Ads',
    vendor: 'AdTech Solutions',
    amount: 5000,
    date: '2024-02-05',
    submittedBy: 'Mike Davis',
    status: 'pending',
  },
  {
    id: 3,
    eventName: 'Product Launch Event',
    category: 'Catering',
    description: 'Coffee & Snacks Setup',
    vendor: 'Premium Catering Co.',
    amount: 2500,
    date: '2024-02-10',
    submittedBy: 'Emily Chen',
    status: 'approved',
    approvedBy: 'Sarah Johnson',
    approvalDate: '2024-02-11',
  },
  {
    id: 4,
    eventName: 'Annual Gala',
    category: 'Entertainment',
    description: 'Live Band Performance',
    vendor: 'Entertainment Plus',
    amount: 8000,
    date: '2024-02-12',
    submittedBy: 'Robert Wilson',
    status: 'pending',
  },
  {
    id: 5,
    eventName: 'Annual Tech Conference 2024',
    category: 'Technology',
    description: 'Projector Rental',
    vendor: 'Tech Events Pro',
    amount: 1200,
    date: '2024-02-14',
    submittedBy: 'Amanda Lee',
    status: 'rejected',
    approvedBy: 'Sarah Johnson',
    approvalDate: '2024-02-15',
    rejectionReason: 'Already included in venue package',
  },
  {
    id: 6,
    eventName: 'Product Launch Event',
    category: 'Marketing',
    description: 'Press Release Distribution',
    vendor: 'PR Newswire',
    amount: 3500,
    date: '2024-02-16',
    submittedBy: 'John Smith',
    status: 'pending',
  },
  {
    id: 7,
    eventName: 'Annual Tech Conference 2024',
    category: 'Catering',
    description: 'Breakfast & Lunch Service',
    vendor: 'Premium Catering Co.',
    amount: 24000,
    date: '2024-02-18',
    submittedBy: 'Emily Chen',
    status: 'approved',
    approvedBy: 'Sarah Johnson',
    approvalDate: '2024-02-19',
  },
  {
    id: 8,
    eventName: 'Annual Gala',
    category: 'Venue',
    description: 'Ballroom Rental',
    vendor: 'Grand Ballroom',
    amount: 25000,
    date: '2024-02-20',
    submittedBy: 'Robert Wilson',
    status: 'approved',
    approvedBy: 'Sarah Johnson',
    approvalDate: '2024-02-21',
  },
  {
    id: 9,
    eventName: 'Industry Summit',
    category: 'Technology',
    description: 'AV Equipment & Setup',
    vendor: 'Tech Events Pro',
    amount: 10500,
    date: '2024-02-22',
    submittedBy: 'James Taylor',
    status: 'approved',
    approvedBy: 'Sarah Johnson',
    approvalDate: '2024-02-23',
  },
  {
    id: 10,
    eventName: 'Annual Tech Conference 2024',
    category: 'Entertainment',
    description: 'Keynote Speaker Fee',
    vendor: 'Speaker Bureau Inc.',
    amount: 20000,
    date: '2024-02-25',
    submittedBy: 'Mike Davis',
    status: 'approved',
    approvedBy: 'Sarah Johnson',
    approvalDate: '2024-02-26',
  },
  {
    id: 11,
    eventName: 'Training Seminar',
    category: 'Venue',
    description: 'Training Center Rental',
    vendor: 'Training Center',
    amount: 8000,
    date: '2024-02-28',
    submittedBy: 'Michael Brown',
    status: 'pending',
  },
  {
    id: 12,
    eventName: 'Client Appreciation Dinner',
    category: 'Catering',
    description: 'Fine Dining Service',
    vendor: 'Fine Dining Restaurant',
    amount: 15000,
    date: '2024-03-01',
    submittedBy: 'Jennifer Lee',
    status: 'approved',
    approvedBy: 'Sarah Johnson',
    approvalDate: '2024-03-02',
  },
  {
    id: 13,
    eventName: 'Charity Fundraiser',
    category: 'Marketing',
    description: 'Event Promotion Campaign',
    vendor: 'Marketing Agency',
    amount: 8000,
    date: '2024-03-05',
    submittedBy: 'Patricia Garcia',
    status: 'pending',
  },
  {
    id: 14,
    eventName: 'Annual Tech Conference 2024',
    category: 'Staffing',
    description: 'Event Staff Services',
    vendor: 'EventStaff Plus',
    amount: 7200,
    date: '2024-03-08',
    submittedBy: 'Amanda Lee',
    status: 'approved',
    approvedBy: 'Sarah Johnson',
    approvalDate: '2024-03-09',
  },
  {
    id: 15,
    eventName: 'Summer Networking Mixer',
    category: 'Venue',
    description: 'Beachfront Hotel Rental',
    vendor: 'Beachfront Hotel',
    amount: 5000,
    date: '2024-03-10',
    submittedBy: 'David Martinez',
    status: 'pending',
  },
  {
    id: 16,
    eventName: 'Industry Summit',
    category: 'Transportation',
    description: 'Shuttle Service',
    vendor: 'Transport Co',
    amount: 4800,
    date: '2024-03-12',
    submittedBy: 'James Taylor',
    status: 'approved',
    approvedBy: 'Sarah Johnson',
    approvalDate: '2024-03-13',
  },
  {
    id: 17,
    eventName: 'Annual Gala',
    category: 'Photography',
    description: 'Event Photography & Videography',
    vendor: 'Photo Pro',
    amount: 6000,
    date: '2024-03-15',
    submittedBy: 'Robert Wilson',
    status: 'approved',
    approvedBy: 'Sarah Johnson',
    approvalDate: '2024-03-16',
  },
  {
    id: 18,
    eventName: 'Product Launch Event',
    category: 'Technology',
    description: 'Event App Development',
    vendor: 'App Developers',
    amount: 12000,
    date: '2024-03-18',
    submittedBy: 'John Smith',
    status: 'pending',
  },
];

// ============================================================================
// BUDGET DEMO DATA
// ============================================================================
export const demoBudgetEvents = [
  { id: '1', name: 'Annual Tech Conference 2024' },
  { id: '2', name: 'Product Launch Event' },
  { id: '3', name: 'Annual Gala' },
  { id: '4', name: 'Workshop Series' },
  { id: '5', name: 'Summer Networking Mixer' },
  { id: '6', name: 'Client Appreciation Dinner' },
  { id: '7', name: 'Training Seminar' },
  { id: '8', name: 'Charity Fundraiser' },
  { id: '9', name: 'Industry Summit' },
];

export const demoBudgetVersions = [
  { id: 'v1', name: 'Initial Budget', date: '2024-01-15', status: 'draft' },
  { id: 'v2', name: 'Revised Budget', date: '2024-02-01', status: 'final' },
  { id: 'v3', name: 'Current Working', date: '2024-02-15', status: 'draft' },
  { id: 'v4', name: 'Q2 Budget Update', date: '2024-03-01', status: 'draft' },
  { id: 'v5', name: 'Final Approved Budget', date: '2024-03-10', status: 'final' },
];

export const demoBudgetItems = [
  { id: 1, category: 'Venue', description: 'Conference Hall Rental', vendor: 'Grand Convention Center', estimatedCost: 45000, actualCost: 45000, status: 'confirmed' },
  { id: 2, category: 'Catering', description: 'Lunch & Refreshments (500 pax)', vendor: 'Premium Catering Co.', estimatedCost: 25000, actualCost: 24000, status: 'confirmed' },
  { id: 3, category: 'Marketing', description: 'Digital Marketing Campaign', vendor: 'AdTech Solutions', estimatedCost: 15000, actualCost: 12000, status: 'partial' },
  { id: 4, category: 'Entertainment', description: 'Keynote Speaker Fee', vendor: 'Speaker Bureau Inc.', estimatedCost: 20000, actualCost: 20000, status: 'confirmed' },
  { id: 5, category: 'Technology', description: 'AV Equipment & Setup', vendor: 'Tech Events Pro', estimatedCost: 12000, actualCost: 10500, status: 'confirmed' },
  { id: 6, category: 'Staffing', description: 'Event Staff (20 people)', vendor: 'EventStaff Plus', estimatedCost: 8000, actualCost: 7200, status: 'confirmed' },
  { id: 7, category: 'Transportation', description: 'Shuttle Service', vendor: 'Transport Co', estimatedCost: 5000, actualCost: 4800, status: 'confirmed' },
  { id: 8, category: 'Decorations', description: 'Event Decor & Signage', vendor: 'Design Studio', estimatedCost: 8000, actualCost: 0, status: 'pending' },
  { id: 9, category: 'Photography', description: 'Event Photography & Videography', vendor: 'Photo Pro', estimatedCost: 6000, actualCost: 6000, status: 'confirmed' },
  { id: 10, category: 'Security', description: 'Security Services', vendor: 'Secure Events', estimatedCost: 4000, actualCost: 4000, status: 'confirmed' },
  { id: 11, category: 'Insurance', description: 'Event Insurance', vendor: 'Insurance Co', estimatedCost: 3000, actualCost: 3000, status: 'confirmed' },
  { id: 12, category: 'Printing', description: 'Name Tags & Programs', vendor: 'Print Shop', estimatedCost: 2000, actualCost: 1800, status: 'confirmed' },
  { id: 13, category: 'Entertainment', description: 'Live Band Performance', vendor: 'Entertainment Plus', estimatedCost: 8000, actualCost: 0, status: 'pending' },
  { id: 14, category: 'Marketing', description: 'Social Media Influencer Campaign', vendor: 'Influencer Agency', estimatedCost: 10000, actualCost: 0, status: 'pending' },
  { id: 15, category: 'Technology', description: 'Event App Development', vendor: 'App Developers', estimatedCost: 15000, actualCost: 12000, status: 'partial' },
];

// ============================================================================
// DASHBOARD DEMO DATA
// ============================================================================
export const demoDashboardStats = [
  { label: 'Active Events', value: '12', change: '+2 this month', color: 'blue', href: '/events?status=Active' },
  { label: 'Total Budget', value: '$485K', change: '+12% from last month', color: 'green', href: '/budget' },
  { label: 'Pending Approvals', value: '8', change: '3 urgent', color: 'yellow', href: '/expenses' },
  { label: 'ROI Average', value: '245%', change: '+18% improvement', color: 'purple', href: '/analytics' },
];

export const demoDashboardBudgetData = [
  { month: 'Jan', budget: 45000, spent: 42000 },
  { month: 'Feb', budget: 52000, spent: 48000 },
  { month: 'Mar', budget: 48000, spent: 51000 },
  { month: 'Apr', budget: 61000, spent: 58000 },
  { month: 'May', budget: 55000, spent: 52000 },
  { month: 'Jun', budget: 67000, spent: 63000 },
];

export const demoDashboardExpenseCategories = [
  { name: 'Venue', value: 35, color: '#3b82f6' },
  { name: 'Catering', value: 28, color: '#10b981' },
  { name: 'Marketing', value: 18, color: '#f59e0b' },
  { name: 'Entertainment', value: 12, color: '#8b5cf6' },
  { name: 'Other', value: 7, color: '#6b7280' },
];

export const demoDashboardRecentEvents = [
  { id: 'demo-1', name: 'Tech Conference 2024', status: 'active', budget: 125000, spent: 98000, progress: 78 },
  { id: 'demo-2', name: 'Product Launch Event', status: 'planning', budget: 85000, spent: 12000, progress: 14 },
  { id: 'demo-3', name: 'Annual Gala', status: 'active', budget: 95000, spent: 87000, progress: 92 },
  { id: 'demo-4', name: 'Workshop Series', status: 'completed', budget: 45000, spent: 44500, progress: 100 },
];

export const demoDashboardAlerts = [
  { id: '1', type: 'approval', message: '3 expense approvals pending', count: 3, urgent: true },
  { id: '2', type: 'overspending', message: 'Annual Gala is 92% over budget', count: 1, urgent: true },
  { id: '3', type: 'document', message: '2 events missing required documents', count: 2, urgent: false },
];

// ============================================================================
// ANALYTICS DEMO DATA
// ============================================================================
export const demoROIMetrics = [
  { event: 'Tech Conf', roi: 245, revenue: 520000, cost: 125000 },
  { event: 'Product Launch', roi: 180, revenue: 238000, cost: 85000 },
  { event: 'Annual Gala', roi: 210, revenue: 290000, cost: 95000 },
  { event: 'Workshop', roi: 195, revenue: 88000, cost: 45000 },
  { event: 'Trade Show', roi: 225, revenue: 337500, cost: 150000 },
];

// ============================================================================
// EXPENSE TRACKER DEMO DATA (Component-specific format)
// ============================================================================
export const demoExpenseTrackerExpenses = [
  {
    id: 1,
    event: 'Annual Tech Conference 2024',
    category: 'Venue',
    item: 'Conference Hall Rental',
    amount: 35000,
    vendor: 'Moscone Center',
    date: '2024-02-15',
    submittedBy: 'Sarah Johnson',
    status: 'approved',
    approver: 'Mike Davis',
    notes: 'Full payment for 3-day rental',
  },
  {
    id: 2,
    event: 'Annual Tech Conference 2024',
    category: 'Catering',
    item: 'Lunch Catering - Day 1',
    amount: 8500,
    vendor: 'Gourmet Catering Co',
    date: '2024-03-15',
    submittedBy: 'Emily Chen',
    status: 'pending',
    notes: '500 attendees x $17 per person',
  },
  {
    id: 3,
    event: 'Product Launch Event',
    category: 'Marketing',
    item: 'Social Media Campaign',
    amount: 12000,
    vendor: 'Digital Marketing Agency',
    date: '2024-02-20',
    submittedBy: 'Mike Davis',
    status: 'approved',
    approver: 'Sarah Johnson',
    notes: 'Month-long campaign',
  },
  {
    id: 4,
    event: 'Annual Tech Conference 2024',
    category: 'Logistics',
    item: 'Event Mobile App',
    amount: 12000,
    vendor: 'TechSolutions Inc',
    date: '2024-01-30',
    submittedBy: 'Sarah Johnson',
    status: 'approved',
    approver: 'Mike Davis',
    notes: 'Custom app development',
  },
];

// ============================================================================
// BUDGET MANAGER DEMO DATA (BudgetLineItem format)
// ============================================================================
export const demoBudgetLineItems = [
  { 
    id: 1, 
    category: 'Venue', 
    subcategory: 'Rental',
    description: 'Conference Hall Rental', 
    estimatedCost: 35000, 
    actualCost: 35000,
    variance: 0,
    status: 'Approved' as const,
    notes: 'Booked for 3 days',
    assignedUser: 'Sarah Johnson',
    lastEditedBy: 'Sarah Johnson',
    lastEditedAt: '2024-03-10T10:30:00Z',
  },
  { 
    id: 2, 
    category: 'Venue', 
    subcategory: 'Equipment',
    description: 'AV Equipment', 
    estimatedCost: 12000, 
    actualCost: 10500,
    variance: 1500,
    status: 'Approved' as const,
    notes: 'Negotiated discount',
    assignedUser: 'Mike Davis',
    lastEditedBy: 'Mike Davis',
    lastEditedAt: '2024-03-08T14:20:00Z',
  },
  { 
    id: 3, 
    category: 'Catering', 
    subcategory: 'Meals',
    description: 'Breakfast & Lunch', 
    estimatedCost: 28000, 
    actualCost: 24000,
    variance: 4000,
    status: 'Approved' as const,
    assignedUser: 'Emily Chen',
    lastEditedBy: 'Emily Chen',
    lastEditedAt: '2024-03-09T09:15:00Z',
  },
];

// ============================================================================
// EVENT NOTES DEMO DATA
// ============================================================================
export const demoEventNotes = [
  {
    id: '1',
    content: 'Venue confirmed for March 15-17. Need to finalize catering menu by end of week.',
    createdAt: '2024-01-15T10:30:00Z',
    updatedAt: '2024-01-15T10:30:00Z',
    createdBy: 'Sarah Johnson',
    tags: ['venue', 'catering', 'urgent'],
  },
  {
    id: '2',
    content: 'Keynote speaker availability confirmed. Contract sent for review.',
    createdAt: '2024-01-20T14:15:00Z',
    updatedAt: '2024-01-20T14:15:00Z',
    createdBy: 'Mike Davis',
    tags: ['speakers', 'contracts'],
  },
  {
    id: '3',
    content: 'Marketing campaign launched. Initial response rate is 15% higher than expected. Consider increasing ad spend.',
    createdAt: '2024-02-01T09:00:00Z',
    updatedAt: '2024-02-05T11:20:00Z',
    createdBy: 'Emily Chen',
    tags: ['marketing', 'budget'],
  },
  {
    id: '4',
    content: 'Follow up with vendor about AV equipment delivery timeline. Need confirmation by Friday.',
    createdAt: '2024-02-10T16:45:00Z',
    updatedAt: '2024-02-10T16:45:00Z',
    createdBy: 'Sarah Johnson',
    tags: ['vendors', 'logistics', 'urgent'],
  },
];

// ============================================================================
// STRATEGIC GOALS DEMO DATA
// ============================================================================
export const demoStrategicGoals = [
  {
    id: '1',
    title: 'Achieve 500+ Attendees',
    description: 'Target attendance for the main conference day',
    targetValue: 500,
    currentValue: 320,
    unit: 'attendees',
    deadline: '2024-03-15',
    status: 'in-progress',
    priority: 'high',
  },
  {
    id: '2',
    title: 'Generate 100 Qualified Leads',
    description: 'Capture contact information from interested participants',
    targetValue: 100,
    currentValue: 45,
    unit: 'leads',
    deadline: '2024-03-17',
    status: 'in-progress',
    priority: 'high',
  },
  {
    id: '3',
    title: 'Maintain Budget Within 5% Variance',
    description: 'Keep actual spending within 5% of planned budget',
    targetValue: 5,
    currentValue: 2.3,
    unit: '%',
    deadline: '2024-03-17',
    status: 'in-progress',
    priority: 'medium',
  },
];

// ============================================================================
// APPROVALS DEMO DATA (ExpenseWithVendor format)
// ============================================================================
export const demoApprovalExpenses = [
  {
    id: '1',
    eventId: '1',
    category: 'Venue',
    title: 'Conference Hall Rental',
    amount: 35000,
    status: 'Pending',
    vendor: 'Moscone Center',
    vendorId: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    event: { id: '1', name: 'Annual Tech Conference 2024' },
    creator: { id: '1', fullName: 'Sarah Johnson', email: 'sarah@example.com' },
  },
  {
    id: '2',
    eventId: '1',
    category: 'Catering',
    title: 'Lunch Catering - Day 1',
    amount: 8500,
    status: 'Pending',
    vendor: 'Gourmet Catering Co',
    vendorId: '2',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    event: { id: '1', name: 'Annual Tech Conference 2024' },
    creator: { id: '2', fullName: 'Emily Chen', email: 'emily@example.com' },
  },
];

// ============================================================================
// EVENT DETAIL DEMO DATA
// ============================================================================
export const demoEventDetail = {
  id: '1',
  name: 'Annual Tech Conference 2024',
  description: 'Annual technology conference featuring keynote speakers and workshops',
  client: 'Tech Corp',
  startDate: '2024-03-15',
  endDate: '2024-03-17',
  status: 'Active',
  createdAt: '2024-01-15',
  updatedAt: '2024-03-10',
  assignments: [
    {
      id: '1',
      role: 'Lead Organizer',
      user: {
        id: '1',
        name: 'Sarah Johnson',
        email: 'sarah@demo.com',
        role: 'EventManager',
      },
    },
  ],
  files: [
    {
      id: '1',
      filename: 'event-plan.pdf',
      mimeType: 'application/pdf',
      size: 245760,
      uploadedAt: '2024-01-20',
    },
  ],
  budgetItems: [
    {
      id: '1',
      category: 'Venue',
      description: 'Conference Hall Rental',
      estimatedCost: 45000,
      actualCost: 45000,
      vendor: 'Grand Convention Center',
    },
    {
      id: '2',
      category: 'Catering',
      description: 'Lunch & Refreshments (500 pax)',
      estimatedCost: 25000,
      actualCost: 24000,
      vendor: 'Premium Catering Co.',
    },
    {
      id: '3',
      category: 'Marketing',
      description: 'Digital Marketing Campaign',
      estimatedCost: 15000,
      actualCost: 12000,
      vendor: 'AdTech Solutions',
    },
  ],
  strategicGoals: [
    {
      id: '1',
      title: 'Achieve 500+ Attendees',
      description: 'Target attendance for the main conference day',
      targetValue: 500,
      currentValue: 320,
      unit: 'attendees',
      deadline: '2024-03-15',
      status: 'in-progress',
      priority: 'high',
    },
    {
      id: '2',
      title: 'Generate 100 Qualified Leads',
      description: 'Capture contact information from interested participants',
      targetValue: 100,
      currentValue: 45,
      unit: 'leads',
      deadline: '2024-03-17',
      status: 'in-progress',
      priority: 'high',
    },
  ],
  _count: {
    files: 5,
    budgetItems: 12,
    activityLogs: 8,
  },
};

// ============================================================================
// EVENT DOCUMENTS DEMO DATA
// ============================================================================
export const demoEventDocuments = [
  {
    id: '1',
    name: 'Event Contract.pdf',
    type: 'application/pdf',
    size: 245760,
    uploadedAt: '2024-01-15T10:30:00Z',
    uploadedBy: 'Sarah Johnson',
  },
  {
    id: '2',
    name: 'Venue Floor Plan.jpg',
    type: 'image/jpeg',
    size: 1024000,
    uploadedAt: '2024-01-20T14:15:00Z',
    uploadedBy: 'Mike Davis',
  },
  {
    id: '3',
    name: 'Budget Spreadsheet.xlsx',
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    size: 512000,
    uploadedAt: '2024-02-01T09:00:00Z',
    uploadedBy: 'Sarah Johnson',
  },
  {
    id: '4',
    name: 'Marketing Materials.zip',
    type: 'application/zip',
    size: 5242880,
    uploadedAt: '2024-02-10T16:45:00Z',
    uploadedBy: 'Emily Chen',
  },
];

// ============================================================================
// STAKEHOLDER MANAGER DEMO DATA
// ============================================================================
export const demoStakeholders = [
  {
    id: '1',
    name: 'John Smith',
    role: 'Client Representative',
    email: 'john@clientcompany.com',
    phone: '+1 (555) 123-4567',
    organization: 'Client Company Inc.',
    notes: 'Primary decision maker',
  },
  {
    id: '2',
    name: 'Emily Chen',
    role: 'Sponsor Contact',
    email: 'emily@sponsor.com',
    phone: '+1 (555) 987-6543',
    organization: 'Sponsor Corp',
    notes: 'Handles sponsorship logistics',
  },
];

// ============================================================================
// TEAM ASSIGNMENTS DEMO DATA
// ============================================================================
export const demoTeamAssignments = [
  {
    id: '1',
    userId: 'user-1',
    role: 'Lead Coordinator',
    assignedBy: 'admin',
    user: {
      name: 'Sarah Johnson',
      email: 'sarah@company.com',
    },
  },
  {
    id: '2',
    userId: 'user-2',
    role: 'Assistant Coordinator',
    assignedBy: 'admin',
    user: {
      name: 'Mike Davis',
      email: 'mike@company.com',
    },
  },
];
