// Demo data for trial users
export const getDemoUser = () => ({
  id: 'demo',
  name: 'Demo User',
  email: 'demo@example.com',
  role: 'individual',
  accountType: 'individual',
  subscription: 'professional', // Give demo users full access
  createdAt: new Date().toISOString(),
  freeEventsRemaining: 999,
});

export const getDemoOrganization = () => ({
  id: 'demo-org',
  name: 'Demo Events Inc.',
  industry: 'Technology',
  size: '51-200',
  address: '123 Event Street',
  city: 'San Francisco',
  country: 'USA',
  website: 'https://demo-events.com',
  description: 'Premier event management company',
  adminId: 'demo',
  subscription: 'professional',
  createdAt: new Date().toISOString(),
  members: [
    {
      id: 'demo',
      name: 'Demo User',
      email: 'demo@example.com',
      role: 'admin',
      joinedAt: new Date().toISOString(),
    },
    {
      id: 'demo-2',
      name: 'Sarah Johnson',
      email: 'sarah@demo-events.com',
      role: 'manager',
      joinedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'demo-3',
      name: 'Mike Davis',
      email: 'mike@demo-events.com',
      role: 'member',
      joinedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    },
  ],
});

export const getDemoEvents = () => [
  {
    id: 'demo-event-1',
    name: 'Annual Tech Conference 2024',
    type: 'Conference',
    date: '2024-03-15',
    endDate: '2024-03-17',
    location: 'San Francisco, CA',
    venue: 'Moscone Center',
    attendees: 500,
    budget: 85000,
    spent: 62000,
    organizer: 'Sarah Johnson',
    status: 'active',
    description: 'Annual technology conference featuring keynote speakers and workshops',
    createdBy: 'demo',
    assignedTo: 'demo-2',
    organizationId: 'demo-org',
    createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-event-2',
    name: 'Product Launch Event',
    type: 'Launch',
    date: '2024-03-20',
    location: 'New York, NY',
    venue: 'Hudson Yards',
    attendees: 200,
    budget: 45000,
    spent: 12000,
    organizer: 'Mike Davis',
    status: 'planning',
    description: 'Launching our new product line with media and influencers',
    createdBy: 'demo',
    assignedTo: 'demo-3',
    organizationId: 'demo-org',
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-event-3',
    name: 'Team Building Retreat',
    type: 'Retreat',
    date: '2024-04-01',
    endDate: '2024-04-03',
    location: 'Lake Tahoe, NV',
    venue: 'Mountain Resort',
    attendees: 50,
    budget: 25000,
    spent: 5000,
    organizer: 'Sarah Johnson',
    status: 'planning',
    description: 'Company-wide team building activities and workshops',
    createdBy: 'demo',
    assignedTo: 'demo-2',
    organizationId: 'demo-org',
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-event-4',
    name: 'Customer Appreciation Day',
    type: 'Social',
    date: '2024-04-10',
    location: 'Los Angeles, CA',
    venue: 'Grand Hotel',
    attendees: 300,
    budget: 35000,
    spent: 28000,
    organizer: 'Mike Davis',
    status: 'active',
    description: 'Annual event to thank our valued customers',
    createdBy: 'demo',
    assignedTo: 'demo-3',
    organizationId: 'demo-org',
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const getDemoVendors = () => [
  {
    id: 'demo-vendor-1',
    name: 'Moscone Center',
    category: 'Venue',
    email: 'events@mosconecenter.com',
    phone: '+1 (415) 974-4000',
    address: '747 Howard St, San Francisco, CA 94103',
    rating: 5,
    totalSpent: 125000,
    eventsCount: 3,
    status: 'active',
    notes: 'Premium venue for large conferences',
    organizationId: 'demo-org',
  },
  {
    id: 'demo-vendor-2',
    name: 'Gourmet Catering Co',
    category: 'Catering',
    email: 'contact@gourmetcatering.com',
    phone: '+1 (415) 555-0100',
    address: '123 Market St, San Francisco, CA 94102',
    rating: 4,
    totalSpent: 85000,
    eventsCount: 8,
    status: 'active',
    notes: 'Reliable catering with diverse menu options',
    organizationId: 'demo-org',
  },
  {
    id: 'demo-vendor-3',
    name: 'Digital Marketing Agency',
    category: 'Marketing',
    email: 'hello@digitalmarketing.com',
    phone: '+1 (415) 555-0200',
    address: '456 Market St, San Francisco, CA 94103',
    rating: 5,
    totalSpent: 65000,
    eventsCount: 5,
    status: 'active',
    notes: 'Excellent social media campaigns',
    organizationId: 'demo-org',
  },
];

export const getDemoExpenses = () => [
  {
    id: 'demo-expense-1',
    eventId: 'demo-event-1',
    category: 'Venue',
    item: 'Conference Hall Rental',
    amount: 35000,
    vendor: 'Moscone Center',
    date: '2024-02-15',
    submittedBy: 'demo-2',
    status: 'approved',
    approvedBy: 'demo',
    notes: 'Full payment for 3-day rental',
    submittedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-expense-2',
    eventId: 'demo-event-1',
    category: 'Catering',
    item: 'Lunch Catering - Day 1',
    amount: 8500,
    vendor: 'Gourmet Catering Co',
    date: '2024-03-15',
    submittedBy: 'demo-3',
    status: 'pending',
    notes: '500 attendees x $17 per person',
    submittedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-expense-3',
    eventId: 'demo-event-2',
    category: 'Marketing',
    item: 'Social Media Campaign',
    amount: 12000,
    vendor: 'Digital Marketing Agency',
    date: '2024-02-20',
    submittedBy: 'demo-3',
    status: 'approved',
    approvedBy: 'demo',
    notes: 'Month-long campaign',
    submittedAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
