/**
 * Vendor-related constants
 */

import { FILTER_DEFAULTS } from "./common";

export const VENDOR_CATEGORIES = {
  ALL: FILTER_DEFAULTS.ALL,
  VENUE: 'Venue',
  CATERING: 'Catering',
  MARKETING: 'Marketing',
  LOGISTICS: 'Logistics',
  ENTERTAINMENT: 'Entertainment',
  STAFF_TRAVEL: 'StaffTravel',
  TECHNOLOGY: 'Technology',
  TRANSPORTATION: 'Transportation',
  MISCELLANEOUS: 'Miscellaneous',
} as const;

export type VendorCategory = typeof VENDOR_CATEGORIES[keyof typeof VENDOR_CATEGORIES];

export const VENDOR_CATEGORY_OPTIONS = [
  { value: VENDOR_CATEGORIES.ALL, label: 'All Categories' },
  { value: VENDOR_CATEGORIES.VENUE, label: VENDOR_CATEGORIES.VENUE },
  { value: VENDOR_CATEGORIES.CATERING, label: VENDOR_CATEGORIES.CATERING },
  { value: VENDOR_CATEGORIES.MARKETING, label: VENDOR_CATEGORIES.MARKETING },
  { value: VENDOR_CATEGORIES.LOGISTICS, label: VENDOR_CATEGORIES.LOGISTICS },
  { value: VENDOR_CATEGORIES.ENTERTAINMENT, label: VENDOR_CATEGORIES.ENTERTAINMENT },
  { value: VENDOR_CATEGORIES.STAFF_TRAVEL, label: VENDOR_CATEGORIES.STAFF_TRAVEL },
  { value: VENDOR_CATEGORIES.TECHNOLOGY, label: VENDOR_CATEGORIES.TECHNOLOGY },
  { value: VENDOR_CATEGORIES.TRANSPORTATION, label: VENDOR_CATEGORIES.TRANSPORTATION },
  { value: VENDOR_CATEGORIES.MISCELLANEOUS, label: VENDOR_CATEGORIES.MISCELLANEOUS },
] as const;

export const VENDOR_CATEGORY_LIST = [
  VENDOR_CATEGORIES.ALL,
  VENDOR_CATEGORIES.VENUE,
  VENDOR_CATEGORIES.CATERING,
  VENDOR_CATEGORIES.MARKETING,
  VENDOR_CATEGORIES.LOGISTICS,
  VENDOR_CATEGORIES.ENTERTAINMENT,
  VENDOR_CATEGORIES.STAFF_TRAVEL,
  VENDOR_CATEGORIES.TECHNOLOGY,
  VENDOR_CATEGORIES.TRANSPORTATION,
  VENDOR_CATEGORIES.MISCELLANEOUS,
] as const;


